package com.nubeclick.pos.dto;
// Generated 07/04/2018 08:40:29 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Closingsales generated by hbm2java
 */
@Entity
@Table(name="closingsales"
    ,catalog="posnubeclick"
)
public class Closingsales  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -2945510734221568807L;
	private int closeId;
     private Cashier cashier;
     private Date closeDate;
     private double closeTotalSale;

    public Closingsales() {
    }

    public Closingsales(int closeId, Cashier cashier, Date closeDate, double closeTotalSale) {
       this.closeId = closeId;
       this.cashier = cashier;
       this.closeDate = closeDate;
       this.closeTotalSale = closeTotalSale;
    }
   
     @Id 

    
    @Column(name="close_id", unique=true, nullable=false)
    public int getCloseId() {
        return this.closeId;
    }
    
    public void setCloseId(int closeId) {
        this.closeId = closeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cashier_id", nullable=false)
    public Cashier getCashier() {
        return this.cashier;
    }
    
    public void setCashier(Cashier cashier) {
        this.cashier = cashier;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="close_date", nullable=false, length=19)
    public Date getCloseDate() {
        return this.closeDate;
    }
    
    public void setCloseDate(Date closeDate) {
        this.closeDate = closeDate;
    }

    
    @Column(name="close_total_sale", nullable=false, precision=22, scale=0)
    public double getCloseTotalSale() {
        return this.closeTotalSale;
    }
    
    public void setCloseTotalSale(double closeTotalSale) {
        this.closeTotalSale = closeTotalSale;
    }




}


