package com.nubeclick.pos.dto;
// Generated 07/04/2018 08:40:29 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="customer"
    ,catalog="posnubeclick"
    , uniqueConstraints = {@UniqueConstraint(columnNames="customer_email"), @UniqueConstraint(columnNames="customer_Lphone"), @UniqueConstraint(columnNames="customer_Mphone")} 
)
public class Customer  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 8487666644306012829L;
	private int customerId;
     private Deliveryaddress deliveryaddress;
     private String customerName;
     private String customerFsurname;
     private String customerSsurname;
     private String customerAddress;
     private String customerLphone;
     private String customerMphone;
     private String customerEmail;
     private Set<Deliveryorder> deliveryorders = new HashSet<Deliveryorder>(0);
     private Set<Sale> sales = new HashSet<Sale>(0);

    public Customer() {
    }

	
    public Customer(int customerId, String customerName, String customerAddress, String customerLphone, String customerMphone, String customerEmail) {
        this.customerId = customerId;
        this.customerName = customerName;
        this.customerAddress = customerAddress;
        this.customerLphone = customerLphone;
        this.customerMphone = customerMphone;
        this.customerEmail = customerEmail;
    }
    public Customer(int customerId, Deliveryaddress deliveryaddress, String customerName, String customerFsurname, String customerSsurname, String customerAddress, String customerLphone, String customerMphone, String customerEmail, Set<Deliveryorder> deliveryorders, Set<Sale> sales) {
       this.customerId = customerId;
       this.deliveryaddress = deliveryaddress;
       this.customerName = customerName;
       this.customerFsurname = customerFsurname;
       this.customerSsurname = customerSsurname;
       this.customerAddress = customerAddress;
       this.customerLphone = customerLphone;
       this.customerMphone = customerMphone;
       this.customerEmail = customerEmail;
       this.deliveryorders = deliveryorders;
       this.sales = sales;
    }
   
     @Id 

    
    @Column(name="customer_id", unique=true, nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="delivery_address_id")
    public Deliveryaddress getDeliveryaddress() {
        return this.deliveryaddress;
    }
    
    public void setDeliveryaddress(Deliveryaddress deliveryaddress) {
        this.deliveryaddress = deliveryaddress;
    }

    
    @Column(name="customer_name", nullable=false, length=100)
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    
    @Column(name="customer_Fsurname", length=100)
    public String getCustomerFsurname() {
        return this.customerFsurname;
    }
    
    public void setCustomerFsurname(String customerFsurname) {
        this.customerFsurname = customerFsurname;
    }

    
    @Column(name="customer_Ssurname", length=100)
    public String getCustomerSsurname() {
        return this.customerSsurname;
    }
    
    public void setCustomerSsurname(String customerSsurname) {
        this.customerSsurname = customerSsurname;
    }

    
    @Column(name="customer_address", nullable=false, length=150)
    public String getCustomerAddress() {
        return this.customerAddress;
    }
    
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }

    
    @Column(name="customer_Lphone", unique=true, nullable=false, length=45)
    public String getCustomerLphone() {
        return this.customerLphone;
    }
    
    public void setCustomerLphone(String customerLphone) {
        this.customerLphone = customerLphone;
    }

    
    @Column(name="customer_Mphone", unique=true, nullable=false, length=45)
    public String getCustomerMphone() {
        return this.customerMphone;
    }
    
    public void setCustomerMphone(String customerMphone) {
        this.customerMphone = customerMphone;
    }

    
    @Column(name="customer_email", unique=true, nullable=false, length=45)
    public String getCustomerEmail() {
        return this.customerEmail;
    }
    
    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customer")
    public Set<Deliveryorder> getDeliveryorders() {
        return this.deliveryorders;
    }
    
    public void setDeliveryorders(Set<Deliveryorder> deliveryorders) {
        this.deliveryorders = deliveryorders;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customer")
    public Set<Sale> getSales() {
        return this.sales;
    }
    
    public void setSales(Set<Sale> sales) {
        this.sales = sales;
    }




}


