package com.nubeclick.pos.dto;
// Generated 07/04/2018 08:40:29 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Deliveryorder generated by hbm2java
 */
@Entity
@Table(name="deliveryorder"
    ,catalog="posnubeclick"
)
public class Deliveryorder  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 7003286393707668317L;
	private int deliveryOrderId;
     private Customer customer;
     private Deliveryaddress deliveryaddress;
     private Saledetail saledetail;
     private Date deliveryDate;
     private String deliveryNotes;

    public Deliveryorder() {
    }

	
    public Deliveryorder(int deliveryOrderId, Customer customer, Deliveryaddress deliveryaddress, Saledetail saledetail) {
        this.deliveryOrderId = deliveryOrderId;
        this.customer = customer;
        this.deliveryaddress = deliveryaddress;
        this.saledetail = saledetail;
    }
    public Deliveryorder(int deliveryOrderId, Customer customer, Deliveryaddress deliveryaddress, Saledetail saledetail, Date deliveryDate, String deliveryNotes) {
       this.deliveryOrderId = deliveryOrderId;
       this.customer = customer;
       this.deliveryaddress = deliveryaddress;
       this.saledetail = saledetail;
       this.deliveryDate = deliveryDate;
       this.deliveryNotes = deliveryNotes;
    }
   
     @Id 

    
    @Column(name="delivery_order_id", unique=true, nullable=false)
    public int getDeliveryOrderId() {
        return this.deliveryOrderId;
    }
    
    public void setDeliveryOrderId(int deliveryOrderId) {
        this.deliveryOrderId = deliveryOrderId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="delivery_address_id", nullable=false)
    public Deliveryaddress getDeliveryaddress() {
        return this.deliveryaddress;
    }
    
    public void setDeliveryaddress(Deliveryaddress deliveryaddress) {
        this.deliveryaddress = deliveryaddress;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="sale_detail_id", referencedColumnName="detail_id", nullable=false), 
        @JoinColumn(name="sale_id", referencedColumnName="sale_id", nullable=false) } )
    public Saledetail getSaledetail() {
        return this.saledetail;
    }
    
    public void setSaledetail(Saledetail saledetail) {
        this.saledetail = saledetail;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="delivery_date", length=19)
    public Date getDeliveryDate() {
        return this.deliveryDate;
    }
    
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    
    @Column(name="delivery_notes", length=16777215)
    public String getDeliveryNotes() {
        return this.deliveryNotes;
    }
    
    public void setDeliveryNotes(String deliveryNotes) {
        this.deliveryNotes = deliveryNotes;
    }




}


