package com.nubeclick.pos.dto;
// Generated 07/04/2018 08:40:29 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Period generated by hbm2java
 */
@Entity
@Table(name="period"
    ,catalog="posnubeclick"
)
public class Period  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -6173853934134410315L;
	private int periodId;
     private Date periodStartDate;
     private Date periodEndDate;
     private double totalSales;
     private double totalPurchases;
     private double totalExpenses;
     private double totalSalaries;

    public Period() {
    }

    public Period(int periodId, Date periodStartDate, Date periodEndDate, double totalSales, double totalPurchases, double totalExpenses, double totalSalaries) {
       this.periodId = periodId;
       this.periodStartDate = periodStartDate;
       this.periodEndDate = periodEndDate;
       this.totalSales = totalSales;
       this.totalPurchases = totalPurchases;
       this.totalExpenses = totalExpenses;
       this.totalSalaries = totalSalaries;
    }
   
     @Id 

    
    @Column(name="period_id", unique=true, nullable=false)
    public int getPeriodId() {
        return this.periodId;
    }
    
    public void setPeriodId(int periodId) {
        this.periodId = periodId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="period_start_date", nullable=false, length=19)
    public Date getPeriodStartDate() {
        return this.periodStartDate;
    }
    
    public void setPeriodStartDate(Date periodStartDate) {
        this.periodStartDate = periodStartDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="period_end_date", nullable=false, length=19)
    public Date getPeriodEndDate() {
        return this.periodEndDate;
    }
    
    public void setPeriodEndDate(Date periodEndDate) {
        this.periodEndDate = periodEndDate;
    }

    
    @Column(name="total_sales", nullable=false, precision=22, scale=0)
    public double getTotalSales() {
        return this.totalSales;
    }
    
    public void setTotalSales(double totalSales) {
        this.totalSales = totalSales;
    }

    
    @Column(name="total_purchases", nullable=false, precision=22, scale=0)
    public double getTotalPurchases() {
        return this.totalPurchases;
    }
    
    public void setTotalPurchases(double totalPurchases) {
        this.totalPurchases = totalPurchases;
    }

    
    @Column(name="total_expenses", nullable=false, precision=22, scale=0)
    public double getTotalExpenses() {
        return this.totalExpenses;
    }
    
    public void setTotalExpenses(double totalExpenses) {
        this.totalExpenses = totalExpenses;
    }

    
    @Column(name="total_salaries", nullable=false, precision=22, scale=0)
    public double getTotalSalaries() {
        return this.totalSalaries;
    }
    
    public void setTotalSalaries(double totalSalaries) {
        this.totalSalaries = totalSalaries;
    }




}


