package com.nubeclick.pos.dto;
// Generated 07/04/2018 08:40:29 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Purchasedetail generated by hbm2java
 */
@Entity
@Table(name = "purchasedetail", catalog = "posnubeclick")
public class Purchasedetail implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 3115151901627178637L;
	private PurchasedetailId id;
	private Product product;
	private Purchase purchase;
	private double productQty;

	public Purchasedetail() {
	}

	public Purchasedetail(PurchasedetailId id, Product product, Purchase purchase, double productQty) {
		this.id = id;
		this.product = product;
		this.purchase = purchase;
		this.productQty = productQty;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "detailId", column = @Column(name = "detail_id", nullable = false, length = 45)),
			@AttributeOverride(name = "purchaseId", column = @Column(name = "purchase_id", nullable = false)) })
	public PurchasedetailId getId() {
		return this.id;
	}

	public void setId(PurchasedetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "purchase_id", nullable = false, insertable = false, updatable = false)
	public Purchase getPurchase() {
		return this.purchase;
	}

	public void setPurchase(Purchase purchase) {
		this.purchase = purchase;
	}

	@Column(name = "product_qty", nullable = false, precision = 22, scale = 0)
	public double getProductQty() {
		return this.productQty;
	}

	public void setProductQty(double productQty) {
		this.productQty = productQty;
	}

}
