package com.nubeclick.pos.dto;
// Generated 07/04/2018 08:40:29 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Purchase generated by hbm2java
 */
@Entity
@Table(name="purchase"
    ,catalog="posnubeclick"
)
public class Purchase  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 3704800577571771407L;
	private int purchaseId;
     private Employee employee;
     private Supplier supplier;
     private Warehouse warehouse;
     private Date purchaseDate;
     private double purchaseTotal;
     private Set<Purchasedetail> purchasedetails = new HashSet<Purchasedetail>(0);

    public Purchase() {
    }

	
    public Purchase(int purchaseId, Employee employee, Supplier supplier, Warehouse warehouse, Date purchaseDate, double purchaseTotal) {
        this.purchaseId = purchaseId;
        this.employee = employee;
        this.supplier = supplier;
        this.warehouse = warehouse;
        this.purchaseDate = purchaseDate;
        this.purchaseTotal = purchaseTotal;
    }
    public Purchase(int purchaseId, Employee employee, Supplier supplier, Warehouse warehouse, Date purchaseDate, double purchaseTotal, Set<Purchasedetail> purchasedetails) {
       this.purchaseId = purchaseId;
       this.employee = employee;
       this.supplier = supplier;
       this.warehouse = warehouse;
       this.purchaseDate = purchaseDate;
       this.purchaseTotal = purchaseTotal;
       this.purchasedetails = purchasedetails;
    }
   
     @Id 

    
    @Column(name="purchase_id", unique=true, nullable=false)
    public int getPurchaseId() {
        return this.purchaseId;
    }
    
    public void setPurchaseId(int purchaseId) {
        this.purchaseId = purchaseId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="supplier_id", nullable=false)
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="warehouse_id", nullable=false)
    public Warehouse getWarehouse() {
        return this.warehouse;
    }
    
    public void setWarehouse(Warehouse warehouse) {
        this.warehouse = warehouse;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="purchase_date", nullable=false, length=19)
    public Date getPurchaseDate() {
        return this.purchaseDate;
    }
    
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    
    @Column(name="purchase_total", nullable=false, precision=22, scale=0)
    public double getPurchaseTotal() {
        return this.purchaseTotal;
    }
    
    public void setPurchaseTotal(double purchaseTotal) {
        this.purchaseTotal = purchaseTotal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="purchase")
    public Set<Purchasedetail> getPurchasedetails() {
        return this.purchasedetails;
    }
    
    public void setPurchasedetails(Set<Purchasedetail> purchasedetails) {
        this.purchasedetails = purchasedetails;
    }




}


