package com.nubeclick.pos.dto;
// Generated 07/04/2018 08:40:29 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PurchasedetailId generated by hbm2java
 */
@Embeddable
public class PurchasedetailId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -8159905848197573441L;
	private String detailId;
     private int purchaseId;

    public PurchasedetailId() {
    }

    public PurchasedetailId(String detailId, int purchaseId) {
       this.detailId = detailId;
       this.purchaseId = purchaseId;
    }
   


    @Column(name="detail_id", nullable=false, length=45)
    public String getDetailId() {
        return this.detailId;
    }
    
    public void setDetailId(String detailId) {
        this.detailId = detailId;
    }


    @Column(name="purchase_id", nullable=false)
    public int getPurchaseId() {
        return this.purchaseId;
    }
    
    public void setPurchaseId(int purchaseId) {
        this.purchaseId = purchaseId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PurchasedetailId) ) return false;
		 PurchasedetailId castOther = ( PurchasedetailId ) other; 
         
		 return ( (this.getDetailId()==castOther.getDetailId()) || ( this.getDetailId()!=null && castOther.getDetailId()!=null && this.getDetailId().equals(castOther.getDetailId()) ) )
 && (this.getPurchaseId()==castOther.getPurchaseId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDetailId() == null ? 0 : this.getDetailId().hashCode() );
         result = 37 * result + this.getPurchaseId();
         return result;
   }   


}


