package com.nubeclick.pos.dto;
// Generated 07/04/2018 08:40:29 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SaledetailId generated by hbm2java
 */
@Embeddable
public class SaledetailId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -4967542577801501574L;
	private int detailId;
     private int saleId;

    public SaledetailId() {
    }

    public SaledetailId(int detailId, int saleId) {
       this.detailId = detailId;
       this.saleId = saleId;
    }
   


    @Column(name="detail_id", unique=true, nullable=false)
    public int getDetailId() {
        return this.detailId;
    }
    
    public void setDetailId(int detailId) {
        this.detailId = detailId;
    }


    @Column(name="sale_id", nullable=false)
    public int getSaleId() {
        return this.saleId;
    }
    
    public void setSaleId(int saleId) {
        this.saleId = saleId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SaledetailId) ) return false;
		 SaledetailId castOther = ( SaledetailId ) other; 
         
		 return (this.getDetailId()==castOther.getDetailId())
 && (this.getSaleId()==castOther.getSaleId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getDetailId();
         result = 37 * result + this.getSaleId();
         return result;
   }   


}


