package com.nubeclick.pos.dto;
// Generated 07/04/2018 08:40:29 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sale generated by hbm2java
 */
@Entity
@Table(name="sale"
    ,catalog="posnubeclick"
)
public class Sale  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 4607819200798788890L;
	private int saleId;
     private Cashier cashier;
     private Customer customer;
     private Date saleDate;
     private double saleTotal;
     private Set<Saledetail> saledetails = new HashSet<Saledetail>(0);

    public Sale() {
    }

	
    public Sale(int saleId, Cashier cashier, Customer customer, Date saleDate, double saleTotal) {
        this.saleId = saleId;
        this.cashier = cashier;
        this.customer = customer;
        this.saleDate = saleDate;
        this.saleTotal = saleTotal;
    }
    public Sale(int saleId, Cashier cashier, Customer customer, Date saleDate, double saleTotal, Set<Saledetail> saledetails) {
       this.saleId = saleId;
       this.cashier = cashier;
       this.customer = customer;
       this.saleDate = saleDate;
       this.saleTotal = saleTotal;
       this.saledetails = saledetails;
    }
   
     @Id 

    
    @Column(name="sale_id", unique=true, nullable=false)
    public int getSaleId() {
        return this.saleId;
    }
    
    public void setSaleId(int saleId) {
        this.saleId = saleId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cashier_id", nullable=false)
    public Cashier getCashier() {
        return this.cashier;
    }
    
    public void setCashier(Cashier cashier) {
        this.cashier = cashier;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="sale_date", nullable=false, length=19)
    public Date getSaleDate() {
        return this.saleDate;
    }
    
    public void setSaleDate(Date saleDate) {
        this.saleDate = saleDate;
    }

    
    @Column(name="sale_total", nullable=false, precision=22, scale=0)
    public double getSaleTotal() {
        return this.saleTotal;
    }
    
    public void setSaleTotal(double saleTotal) {
        this.saleTotal = saleTotal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sale")
    public Set<Saledetail> getSaledetails() {
        return this.saledetails;
    }
    
    public void setSaledetails(Set<Saledetail> saledetails) {
        this.saledetails = saledetails;
    }




}


