package com.nubeclick.pos.dto;
// Generated 07/04/2018 08:40:29 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Saledetail generated by hbm2java
 */
@Entity
@Table(name="saledetail"
    ,catalog="posnubeclick"
    , uniqueConstraints = @UniqueConstraint(columnNames="detail_id") 
)
public class Saledetail  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 4096612227262419823L;
	private SaledetailId id;
     private Product product;
     private Sale sale;
     private double productQty;
     private Set<Deliveryorder> deliveryorders = new HashSet<Deliveryorder>(0);

    public Saledetail() {
    }

	
    public Saledetail(SaledetailId id, Product product, Sale sale, double productQty) {
        this.id = id;
        this.product = product;
        this.sale = sale;
        this.productQty = productQty;
    }
    public Saledetail(SaledetailId id, Product product, Sale sale, double productQty, Set<Deliveryorder> deliveryorders) {
       this.id = id;
       this.product = product;
       this.sale = sale;
       this.productQty = productQty;
       this.deliveryorders = deliveryorders;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="detailId", column=@Column(name="detail_id", unique=true, nullable=false) ), 
        @AttributeOverride(name="saleId", column=@Column(name="sale_id", nullable=false) ) } )
    public SaledetailId getId() {
        return this.id;
    }
    
    public void setId(SaledetailId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sale_id", nullable=false, insertable=false, updatable=false)
    public Sale getSale() {
        return this.sale;
    }
    
    public void setSale(Sale sale) {
        this.sale = sale;
    }

    
    @Column(name="product_qty", nullable=false, precision=22, scale=0)
    public double getProductQty() {
        return this.productQty;
    }
    
    public void setProductQty(double productQty) {
        this.productQty = productQty;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="saledetail")
    public Set<Deliveryorder> getDeliveryorders() {
        return this.deliveryorders;
    }
    
    public void setDeliveryorders(Set<Deliveryorder> deliveryorders) {
        this.deliveryorders = deliveryorders;
    }




}


