package com.nubeclick.pos.dto;
// Generated 07/04/2018 08:40:29 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name="supplier"
    ,catalog="posnubeclick"
)
public class Supplier  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -7478411034618014703L;
	private int supplierId;
     private String supplierName;
     private String supplierFsurname;
     private String supplierSsurname;
     private String supplierAddress;
     private String suplierLocation;
     private String supplierCity;
     private String supplierLphone;
     private String supplierMphone;
     private String supplierEmail;
     private Set<Purchase> purchases = new HashSet<Purchase>(0);

    public Supplier() {
    }

	
    public Supplier(int supplierId, String supplierName, String supplierAddress, String supplierLphone) {
        this.supplierId = supplierId;
        this.supplierName = supplierName;
        this.supplierAddress = supplierAddress;
        this.supplierLphone = supplierLphone;
    }
    public Supplier(int supplierId, String supplierName, String supplierFsurname, String supplierSsurname, String supplierAddress, String suplierLocation, String supplierCity, String supplierLphone, String supplierMphone, String supplierEmail, Set<Purchase> purchases) {
       this.supplierId = supplierId;
       this.supplierName = supplierName;
       this.supplierFsurname = supplierFsurname;
       this.supplierSsurname = supplierSsurname;
       this.supplierAddress = supplierAddress;
       this.suplierLocation = suplierLocation;
       this.supplierCity = supplierCity;
       this.supplierLphone = supplierLphone;
       this.supplierMphone = supplierMphone;
       this.supplierEmail = supplierEmail;
       this.purchases = purchases;
    }
   
     @Id 

    
    @Column(name="supplier_id", unique=true, nullable=false)
    public int getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(int supplierId) {
        this.supplierId = supplierId;
    }

    
    @Column(name="supplier_name", nullable=false, length=150)
    public String getSupplierName() {
        return this.supplierName;
    }
    
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    
    @Column(name="supplier_Fsurname", length=100)
    public String getSupplierFsurname() {
        return this.supplierFsurname;
    }
    
    public void setSupplierFsurname(String supplierFsurname) {
        this.supplierFsurname = supplierFsurname;
    }

    
    @Column(name="supplier_Ssurname", length=100)
    public String getSupplierSsurname() {
        return this.supplierSsurname;
    }
    
    public void setSupplierSsurname(String supplierSsurname) {
        this.supplierSsurname = supplierSsurname;
    }

    
    @Column(name="supplier_address", nullable=false, length=150)
    public String getSupplierAddress() {
        return this.supplierAddress;
    }
    
    public void setSupplierAddress(String supplierAddress) {
        this.supplierAddress = supplierAddress;
    }

    
    @Column(name="suplier_location", length=100)
    public String getSuplierLocation() {
        return this.suplierLocation;
    }
    
    public void setSuplierLocation(String suplierLocation) {
        this.suplierLocation = suplierLocation;
    }

    
    @Column(name="supplier_city", length=100)
    public String getSupplierCity() {
        return this.supplierCity;
    }
    
    public void setSupplierCity(String supplierCity) {
        this.supplierCity = supplierCity;
    }

    
    @Column(name="supplier_Lphone", nullable=false, length=45)
    public String getSupplierLphone() {
        return this.supplierLphone;
    }
    
    public void setSupplierLphone(String supplierLphone) {
        this.supplierLphone = supplierLphone;
    }

    
    @Column(name="supplier_Mphone", length=45)
    public String getSupplierMphone() {
        return this.supplierMphone;
    }
    
    public void setSupplierMphone(String supplierMphone) {
        this.supplierMphone = supplierMphone;
    }

    
    @Column(name="supplier_email", length=45)
    public String getSupplierEmail() {
        return this.supplierEmail;
    }
    
    public void setSupplierEmail(String supplierEmail) {
        this.supplierEmail = supplierEmail;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="supplier")
    public Set<Purchase> getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Set<Purchase> purchases) {
        this.purchases = purchases;
    }




}


