package com.nubeclick.pos.dto;
// Generated 07/04/2018 08:40:29 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "posnubeclick")
@NamedQuery(name = "User.Login", query = "select u from User u where u.userLogin = :userLogin and u.userPwd = :userPwd")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8132998857853632894L;
	private int userId;
	private Role role;
	private String userName;
	private String userLogin;
	private String userPwd;
	private Set<Cashier> cashiers = new HashSet<Cashier>(0);
	private Set<Employee> employees = new HashSet<Employee>(0);

	public User() {
	}

	public User(int userId, Role role, String userName, String userLogin, String userPwd) {
		this.userId = userId;
		this.role = role;
		this.userName = userName;
		this.userLogin = userLogin;
		this.userPwd = userPwd;
	}

	public User(int userId, Role role, String userName, String userLogin, String userPwd, Set<Cashier> cashiers,
			Set<Employee> employees) {
		this.userId = userId;
		this.role = role;
		this.userName = userName;
		this.userLogin = userLogin;
		this.userPwd = userPwd;
		this.cashiers = cashiers;
		this.employees = employees;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "user_name", nullable = false, length = 150)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_login", nullable = false, length = 150)
	public String getUserLogin() {
		return this.userLogin;
	}

	public void setUserLogin(String userLogin) {
		this.userLogin = userLogin;
	}

	@Column(name = "user_pwd", nullable = false, length = 45)
	public String getUserPwd() {
		return this.userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Cashier> getCashiers() {
		return this.cashiers;
	}

	public void setCashiers(Set<Cashier> cashiers) {
		this.cashiers = cashiers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
